.TH "Xfilter-FTL" "8" "xfilter-FTL" "X-filter" "June 2018"
.SH "NAME"
xfilter-FTL - X-filter : The Faster-Than-Light (FTL) Engine
.br
.SH "SYNOPSIS"
\fBservice xfilter-FTL \fR(\fBstart\fR|\fBstop\fR|\fBrestart\fR)
.br

\fBxfilter-FTL debug\fR
.br
\fBxfilter-FTL test\fR
.br
\fBxfilter-FTL -v\fR
.br
\fBxfilter-FTL -t\fR
.br
\fBxfilter-FTL -b\fR
.br
\fBxfilter-FTL -f\fR
.br
\fBxfilter-FTL -h\fR
.br
\fBxfilter-FTL dnsmasq-test\fR
.br
\fBxfilter-FTL --\fR (\fBoptions\fR)
.br

.SH "DESCRIPTION"
X-filter : The Faster-Than-Light (FTL) Engine is a lightweight, purpose-built daemon used to provide statistics needed for the X-filter Web Interface, and its API can be easily integrated into your own projects. Although it is an optional component of the X-filter ecosystem, it will be installed by default to provide statistics. As the name implies, FTL does its work \fIvery\fR \fIquickly\fR!
.br

Usage
.br

\fBservice xfilter-FTL start\fR
.br
    Start the xfilter-FTL daemon
.br

\fBservice xfilter-FTL stop\fR
.br
    Stop the xfilter-FTL daemon
.br

\fBservice xfilter-FTL restart\fR
.br
    If the xfilter-FTP daemon is running, stop and then start, otherwise start.
.br

Command line arguments
.br

\fBdebug\fR
.br
    Don't go into daemon mode (stay in foreground) + more verbose logging
.br

\fBtest\fR
.br
    Start FTL and process everything, but shut down immediately afterwards
.br

\fB-v, version\fR
.br
    Don't start FTL, show only version
.br

\fB-t, tag\fR
.br
    Don't start FTL, show only git tag
.br

\fB-b, branch\fR
.br
    Don't start FTL, show only git branch FTL was compiled from
.br

\fB-f, no-daemon\fR
.br
    Don't go into background (daemon mode)
.br

\fB-h, help\fR
.br
    Don't start FTL, show help
.br

\fBdnsmasq-test\fR
.br
    Test resolver config file syntax
.br

\fB--\fR  (options)
.br
    Pass options to internal dnsmasq resolver
.br
.SH "EXAMPLE"
Command line arguments can be arbitrarily combined, e.g:
.br

\fBxfilter-FTL debug test\fR
.br

Start ftl in foreground with more verbose logging, process everything and shutdown immediately
.br
.SH "SEE ALSO"
\fBxfilter\fR(8), \fBxfilter-FTL.conf\fR(5)
.br
.SH "COLOPHON"

Get sucked into the latest news and community activity by entering X-filter's orbit. Information about X-filter, and the latest version of the software can be found at https://x-filter.net
.br
